config/routes.rb
WholeGenome::Application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :genomes do 
          get :content, on: :member
        end
      end
    end
  end
  root :to => 'home#index'

end

app/models/api_key.rb
class ApiKey
  include Mongoid::Document
  field :access_token

  before_create :generate_access_token
  
  private
  
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

end

app/models/genome.rb
class Genome
  include Mongoid::Document
  include Mongoid::Timestamps::Updated

  field :format, type: String
  # embedded_in :user # , :inverse_of => :provider
  belongs_to :user # , :inverse_of => :provider

  mount_uploader :content, GenomeUploader


end

app/models/user.rb
class User
  include Mongoid::Document
  field :ehr_identifier
  field :healthcare_identifier

  has_many :genomes
  # embeds_many :genomes, cascade_callbacks: true
end

app/controllers/api/v1/genomes_controller.rb
class Api::V1::GenomesController < ApplicationController
  respond_to :json

  # GET /genomes
  # GET /genomes.json
  def index
    @genomes = user.genomes

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @genomes }
    # end
  end

  def content
    content = Genome.find(params[:id]).content
    response.etag = [content.file.md5]
    if request.fresh?(response)
      head :not_modified
    else
      send_data content.read
    end
  end
  def upload 
    uploaded_io = params[:genome][:content]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'w') do |file|
      file.write(uploaded_io.read)
    end
  end

  private

  def user
    @user = User.where(:ehr_identifier => params[:id])
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  respond_to :json

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.where(:ehr_identifier => params[:id])
    # @user = User.find(params[:id])
  end

  def restrict_access
    authenticate_or_request_with_http_token do |token, options|
      ApiKey.exists?(access_token: token)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/genomes_controller.rb
class GenomesController < ApplicationController

  # GET /genomes
  # GET /genomes.json
  def index
    @genomes = Genome.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genomes }
    end
  end

  # GET /genomes/1
  # GET /genomes/1.json
  def show
    @genome = Genome.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genome }
    end
  end

  # GET /genomes/new
  # GET /genomes/new.json
  def new
    @genome = Genome.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genome }
    end
  end

  # GET /genomes/1/edit
  def edit
    @genome = Genome.find(params[:id])
  end

  # POST /genomes
  # POST /genomes.json
  def create
    @genome = Genome.new(params[:genome])

    respond_to do |format|
      if @genome.save
        format.html { redirect_to @genome, notice: 'Genome was successfully created.' }
        format.json { render json: @genome, status: :created, location: @genome }
      else
        format.html { render action: "new" }
        format.json { render json: @genome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genomes/1
  # PUT /genomes/1.json
  def update
    @genome = Genome.find(params[:id])

    respond_to do |format|
      if @genome.update_attributes(params[:genome])
        format.html { redirect_to @genome, notice: 'Genome was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genomes/1
  # DELETE /genomes/1.json
  def destroy
    @genome = Genome.find(params[:id])
    @genome.destroy

    respond_to do |format|
      format.html { redirect_to genomes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/api/v1/genomes_helper.rb
module Api::V1::GenomesHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genomes_helper.rb
module GenomesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genomes/_form.html.erb
<%= form_for(@genome) do |f| %>
  <% if @genome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genome.errors.count, "error") %> prohibited this genome from being saved:</h2>

      <ul>
      <% @genome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :format %><br />
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.file_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genomes/edit.html.erb
<h1>Editing genome</h1>

<%= render 'form' %>

<%= link_to 'Show', @genome %> |
<%= link_to 'Back', genomes_path %>

app/views/genomes/index.html.erb
<h1>Listing genomes</h1>

<table>
  <tr>
    <th>Format</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @genomes.each do |genome| %>
  <tr>
    <td><%= genome.format %></td>
    <td><%= link_to 'Show', genome %></td>
    <td><%= link_to 'Edit', edit_genome_path(genome) %></td>
    <td><%= link_to 'Destroy', genome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Genome', new_genome_path %>

app/views/genomes/new.html.erb
<h1>New genome</h1>

<%= render 'form' %>

<%= link_to 'Back', genomes_path %>

app/views/genomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Format:</b>
  <%= @genome.format %>
</p>


<%= link_to 'Edit', edit_genome_path(@genome) %> |
<%= link_to 'Back', genomes_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WholeGenome</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :healthcare_identifier %><br />
    <%= f.text_field :healthcare_identifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Healthcare identifier</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.healthcare_identifier %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Healthcare identifier:</b>
  <%= @user.healthcare_identifier %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>